GET localhost:8080/restws/services/patientservice/patients

#GET localhost:8080/restws/services/patientservice/patients/123

#POST localhost:8080/restws/services/patientservice/patients
#
#<Patient>
#<name>Santhosh</name>
#</Patient>

#PUT localhost:8080/restws/services/patientservice/patients
#
#<Patient>
#<id>124</id>
#<name>Wei</name>
#</Patient>

#DELETE localhost:8080/restws/services/patientservice/patients/123